// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: comment.proto

package server

import (
	"context"

	"comment-rpc/comment"
	"comment-rpc/internal/logic"
	"comment-rpc/internal/svc"
)

type CommentServiceServer struct {
	svcCtx *svc.ServiceContext
	comment.UnimplementedCommentServiceServer
}

func NewCommentServiceServer(svcCtx *svc.ServiceContext) *CommentServiceServer {
	return &CommentServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentServiceServer) CreateComment(ctx context.Context, in *comment.CreateCommentRequest) (*comment.Comment, error) {
	l := logic.NewCreateCommentLogic(ctx, s.svcCtx)
	return l.CreateComment(in)
}

func (s *CommentServiceServer) DeleteComment(ctx context.Context, in *comment.DeleteCommentRequest) (*comment.Empty, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}

func (s *CommentServiceServer) ListRootComments(ctx context.Context, in *comment.ListRootCommentsRequest) (*comment.CommentPageResponse, error) {
	l := logic.NewListRootCommentsLogic(ctx, s.svcCtx)
	return l.ListRootComments(in)
}

func (s *CommentServiceServer) ListSubComments(ctx context.Context, in *comment.ListSubCommentsRequest) (*comment.CommentPageResponse, error) {
	l := logic.NewListSubCommentsLogic(ctx, s.svcCtx)
	return l.ListSubComments(in)
}
