// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: search.proto

package server

import (
	"context"

	"search-rpc/internal/logic"
	"search-rpc/internal/svc"
	"search-rpc/search"
)

type SearchServiceServer struct {
	svcCtx *svc.ServiceContext
	search.UnimplementedSearchServiceServer
}

func NewSearchServiceServer(svcCtx *svc.ServiceContext) *SearchServiceServer {
	return &SearchServiceServer{
		svcCtx: svcCtx,
	}
}

// 核心搜索 (对应 Java: searchPosts)
func (s *SearchServiceServer) Search(ctx context.Context, in *search.SearchRequest) (*search.SearchResponse, error) {
	l := logic.NewSearchLogic(ctx, s.svcCtx)
	return l.Search(in)
}

// 搜索补全 (对应 Java: getSearchSuggestions)
func (s *SearchServiceServer) Suggest(ctx context.Context, in *search.SuggestRequest) (*search.SuggestResponse, error) {
	l := logic.NewSuggestLogic(ctx, s.svcCtx)
	return l.Suggest(in)
}

// 获取搜索历史 (对应 Java: getSearchHistory)
func (s *SearchServiceServer) GetHistory(ctx context.Context, in *search.HistoryRequest) (*search.HistoryResponse, error) {
	l := logic.NewGetHistoryLogic(ctx, s.svcCtx)
	return l.GetHistory(in)
}

// 删除搜索历史 (对应 Java: clearSearchHistory / deleteSearchHistoryItem)
func (s *SearchServiceServer) DeleteHistory(ctx context.Context, in *search.ClearHistoryRequest) (*search.Empty, error) {
	l := logic.NewDeleteHistoryLogic(ctx, s.svcCtx)
	return l.DeleteHistory(in)
}
