// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AuthChangePwdReq struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type AuthLoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type AuthRefreshReq struct {
	RefreshToken string `json:"refreshToken"`
}

type AuthRegisterReq struct {
	Email    string `json:"email"`
	Code     string `json:"code"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
}

type AuthResetPwdReq struct {
	Email       string `json:"email"`
	Code        string `json:"code"`
	NewPassword string `json:"newPassword"`
}

type AuthResponse struct {
	Tokens TokenPair   `json:"tokens"`
	User   UserSummary `json:"user"`
}

type AuthSendCodeReq struct {
	Email string `json:"email"`
}

type BindEmailReq struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}

type Empty struct {
}

type HistoryReq struct {
	Keyword string `form:"keyword,optional"`
}

type IdPath struct {
	Id int64 `path:"id"`
}

type InteractionReq struct {
	TargetId string `json:"targetId"`
}

type PostIdPath struct {
	PostId string `path:"postId"`
}

type RatePostReq struct {
	TargetId string  `json:"targetId"`
	Score    float64 `json:"score"`
}

type SearchReq struct {
	Keyword  string `form:"keyword,optional"`
	Tag      string `form:"tag,optional"`
	Page     int32  `form:"page,optional"`
	PageSize int32  `form:"pageSize,optional"`
	Size     int32  `form:"size,optional"`
	Sort     string `form:"sort,optional"`
}

type SendEmailCodeResp struct {
	NextRetrySeconds int32 `json:"nextRetrySeconds"`
}

type SuggestReq struct {
	Keyword string `form:"keyword"`
}

type TokenPair struct {
	AccessToken   string `json:"accessToken"`
	RefreshToken  string `json:"refreshToken"`
	TokenType     string `json:"tokenType"`
	AccessExpire  int64  `json:"accessExpire"`
	RefreshExpire int64  `json:"refreshExpire"`
}

type UpdateProfileReq struct {
	Nickname string `json:"nickname,optional"`
	Avatar   string `json:"avatar,optional"`
	Bio      string `json:"bio,optional"`
	Gender   int32  `json:"gender,optional"`
	Birthday string `json:"birthday,optional"`
	Region   string `json:"region,optional"`
}

type UploadReq struct {
	File string `form:"file"`
}

type PostAuthor struct {
	UserId   string `json:"userId"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}

type PostVO struct {
	Id            string     `json:"id"`
	Author        PostAuthor `json:"author"`
	Title         string     `json:"title"`
	Content       string     `json:"content"`
	Type          int32      `json:"type"`
	Cover         string     `json:"cover"`
	Images        []string   `json:"images"`
	Video         string     `json:"video"`
	LikeCount     int32      `json:"likeCount"`
	CollectCount  int32      `json:"collectCount"`
	CommentCount  int32      `json:"commentCount"`
	IsLiked       bool       `json:"isLiked"`
	IsCollected   bool       `json:"isCollected"`
	IsFollowed    bool       `json:"isFollowed"`
	RatingAverage float64    `json:"ratingAverage"`
	RatingCount   int32      `json:"ratingCount"`
	MyScore       float64    `json:"myScore"`
	CreatedAt     string     `json:"createdAt"`
	Tags          []string   `json:"tags"`
	CoverWidth    int32      `json:"coverWidth"`
	CoverHeight   int32      `json:"coverHeight"`
}

type PageResultPost struct {
	Records []PostVO `json:"records"`
	Total   int64    `json:"total"`
	Current int32    `json:"current"`
	Size    int32    `json:"size"`
}

type SearchSuggestResp struct {
	Suggestions []string `json:"suggestions"`
}

type SearchHistoryResp struct {
	Keywords []string `json:"keywords"`
}

type UserProfile struct {
	UserId            int64  `json:"userId"`
	Email             string `json:"email"`
	Nickname          string `json:"nickname"`
	Avatar            string `json:"avatar"`
	Bio               string `json:"bio"`
	Gender            int32  `json:"gender"`
	Birthday          string `json:"birthday"`
	Region            string `json:"region"`
	Role              string `json:"role"`
	Status            int32  `json:"status"`
	FollowCount       int64  `json:"followCount"`
	FanCount          int64  `json:"fanCount"`
	ReceivedLikeCount int64  `json:"receivedLikeCount"`
}

type PublicUserProfile struct {
	UserId            int64  `json:"userId"`
	Nickname          string `json:"nickname"`
	Avatar            string `json:"avatar"`
	Bio               string `json:"bio"`
	Gender            int32  `json:"gender"`
	Region            string `json:"region"`
	FollowCount       int64  `json:"followCount"`
	FanCount          int64  `json:"fanCount"`
	ReceivedLikeCount int64  `json:"receivedLikeCount"`
	IsFollowed        bool   `json:"isFollowed"`
}

type UserIdPath struct {
	UserId int64 `path:"userId"`
}

type UserSummary struct {
	UserId   int64  `json:"userId"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Role     string `json:"role"`
	Status   int32  `json:"status"`
}
