server:
  port: 8080
  servlet:
    context-path: /
  undertow:
    threads:
      io: 2
      worker: 100
    buffer-size: 16384
    direct-buffers: true

spring:
  application:
    name: afternoon3-backend
  profiles:
    # 默认激活 dev 环境。如果在服务器上跑，可以在启动时用 --spring.profiles.active=prod 覆盖它
    active: dev

  # JSON 序列化规则（全环境通用）
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always

  # 文件上传限制（全环境通用）
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

# MyBatis-Plus 全局结构规则（全环境通用）
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.szu.afternoon3.platform.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

# 业务通用常量
szu:
  jwt:
    expiration: 604800 # 7天过期规则不变
  oss:
    default-avatar: https://afternoon3-rednote.oss-cn-shenzhen.aliyuncs.com/default_avatar.jpg

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    mail:
      enabled: false