// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/search/search.proto

package search

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// =======================
// 1. 核心搜索接口
// =======================
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`                    // 关键词
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`                            // 标签筛选
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 页码 (从1开始)
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	Sort          string                 `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`                          // 排序策略 (hot, new, etc.)
	UserId        int64                  `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 当前用户ID (用于记录搜索历史)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_search_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *SearchRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 搜索返回的单条帖子摘要
type SearchPostVO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"` // 摘要
	Cover         string                 `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	LikeCount     int32                  `protobuf:"varint,6,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	Author        *UserVO                `protobuf:"bytes,7,opt,name=author,proto3" json:"author,omitempty"` // 嵌套结构
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	CoverWidth    int32                  `protobuf:"varint,9,opt,name=cover_width,json=coverWidth,proto3" json:"cover_width,omitempty"`
	CoverHeight   int32                  `protobuf:"varint,10,opt,name=cover_height,json=coverHeight,proto3" json:"cover_height,omitempty"`
	IsLiked       bool                   `protobuf:"varint,11,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"` // Go 端如果不方便查，可以留空，Java 补全
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPostVO) Reset() {
	*x = SearchPostVO{}
	mi := &file_proto_search_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPostVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPostVO) ProtoMessage() {}

func (x *SearchPostVO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPostVO.ProtoReflect.Descriptor instead.
func (*SearchPostVO) Descriptor() ([]byte, []int) {
	return file_proto_search_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchPostVO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchPostVO) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchPostVO) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SearchPostVO) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *SearchPostVO) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *SearchPostVO) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *SearchPostVO) GetAuthor() *UserVO {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *SearchPostVO) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SearchPostVO) GetCoverWidth() int32 {
	if x != nil {
		return x.CoverWidth
	}
	return 0
}

func (x *SearchPostVO) GetCoverHeight() int32 {
	if x != nil {
		return x.CoverHeight
	}
	return 0
}

func (x *SearchPostVO) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

type UserVO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserVO) Reset() {
	*x = UserVO{}
	mi := &file_proto_search_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserVO) ProtoMessage() {}

func (x *UserVO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserVO.ProtoReflect.Descriptor instead.
func (*UserVO) Descriptor() ([]byte, []int) {
	return file_proto_search_search_proto_rawDescGZIP(), []int{2}
}

func (x *UserVO) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserVO) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserVO) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SearchPostVO        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_search_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResponse) GetItems() []*SearchPostVO {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SuggestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestRequest) Reset() {
	*x = SuggestRequest{}
	mi := &file_proto_search_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestRequest) ProtoMessage() {}

func (x *SuggestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestRequest.ProtoReflect.Descriptor instead.
func (*SuggestRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_search_proto_rawDescGZIP(), []int{4}
}

func (x *SuggestRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type SuggestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestions   []string               `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestResponse) Reset() {
	*x = SuggestResponse{}
	mi := &file_proto_search_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestResponse) ProtoMessage() {}

func (x *SuggestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestResponse.ProtoReflect.Descriptor instead.
func (*SuggestResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_search_proto_rawDescGZIP(), []int{5}
}

func (x *SuggestResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_proto_search_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_search_proto_rawDescGZIP(), []int{6}
}

func (x *HistoryRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keywords      []string               `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_proto_search_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_search_proto_rawDescGZIP(), []int{7}
}

func (x *HistoryResponse) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

type ClearHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"` // 如果为空则全删
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearHistoryRequest) Reset() {
	*x = ClearHistoryRequest{}
	mi := &file_proto_search_search_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearHistoryRequest) ProtoMessage() {}

func (x *ClearHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearHistoryRequest.ProtoReflect.Descriptor instead.
func (*ClearHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_search_proto_rawDescGZIP(), []int{8}
}

func (x *ClearHistoryRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ClearHistoryRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_search_search_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_search_search_proto_rawDescGZIP(), []int{9}
}

var File_proto_search_search_proto protoreflect.FileDescriptor

const file_proto_search_search_proto_rawDesc = "" +
	"\n" +
	"\x19proto/search/search.proto\x12\x06search\"\x99\x01\n" +
	"\rSearchRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\tR\x04sort\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\x03R\x06userId\"\xb2\x02\n" +
	"\fSearchPostVO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05cover\x18\x04 \x01(\tR\x05cover\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\x12\x1d\n" +
	"\n" +
	"like_count\x18\x06 \x01(\x05R\tlikeCount\x12&\n" +
	"\x06author\x18\a \x01(\v2\x0e.search.UserVOR\x06author\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x1f\n" +
	"\vcover_width\x18\t \x01(\x05R\n" +
	"coverWidth\x12!\n" +
	"\fcover_height\x18\n" +
	" \x01(\x05R\vcoverHeight\x12\x19\n" +
	"\bis_liked\x18\v \x01(\bR\aisLiked\"U\n" +
	"\x06UserVO\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"R\n" +
	"\x0eSearchResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.search.SearchPostVOR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"*\n" +
	"\x0eSuggestRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\"3\n" +
	"\x0fSuggestResponse\x12 \n" +
	"\vsuggestions\x18\x01 \x03(\tR\vsuggestions\")\n" +
	"\x0eHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"-\n" +
	"\x0fHistoryResponse\x12\x1a\n" +
	"\bkeywords\x18\x01 \x03(\tR\bkeywords\"H\n" +
	"\x13ClearHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\"\a\n" +
	"\x05Empty2\x80\x02\n" +
	"\rSearchService\x127\n" +
	"\x06Search\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponse\x12:\n" +
	"\aSuggest\x12\x16.search.SuggestRequest\x1a\x17.search.SuggestResponse\x12=\n" +
	"\n" +
	"GetHistory\x12\x16.search.HistoryRequest\x1a\x17.search.HistoryResponse\x12;\n" +
	"\rDeleteHistory\x12\x1b.search.ClearHistoryRequest\x1a\r.search.EmptyB\n" +
	"Z\b./searchb\x06proto3"

var (
	file_proto_search_search_proto_rawDescOnce sync.Once
	file_proto_search_search_proto_rawDescData []byte
)

func file_proto_search_search_proto_rawDescGZIP() []byte {
	file_proto_search_search_proto_rawDescOnce.Do(func() {
		file_proto_search_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_search_search_proto_rawDesc), len(file_proto_search_search_proto_rawDesc)))
	})
	return file_proto_search_search_proto_rawDescData
}

var file_proto_search_search_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_search_search_proto_goTypes = []any{
	(*SearchRequest)(nil),       // 0: search.SearchRequest
	(*SearchPostVO)(nil),        // 1: search.SearchPostVO
	(*UserVO)(nil),              // 2: search.UserVO
	(*SearchResponse)(nil),      // 3: search.SearchResponse
	(*SuggestRequest)(nil),      // 4: search.SuggestRequest
	(*SuggestResponse)(nil),     // 5: search.SuggestResponse
	(*HistoryRequest)(nil),      // 6: search.HistoryRequest
	(*HistoryResponse)(nil),     // 7: search.HistoryResponse
	(*ClearHistoryRequest)(nil), // 8: search.ClearHistoryRequest
	(*Empty)(nil),               // 9: search.Empty
}
var file_proto_search_search_proto_depIdxs = []int32{
	2, // 0: search.SearchPostVO.author:type_name -> search.UserVO
	1, // 1: search.SearchResponse.items:type_name -> search.SearchPostVO
	0, // 2: search.SearchService.Search:input_type -> search.SearchRequest
	4, // 3: search.SearchService.Suggest:input_type -> search.SuggestRequest
	6, // 4: search.SearchService.GetHistory:input_type -> search.HistoryRequest
	8, // 5: search.SearchService.DeleteHistory:input_type -> search.ClearHistoryRequest
	3, // 6: search.SearchService.Search:output_type -> search.SearchResponse
	5, // 7: search.SearchService.Suggest:output_type -> search.SuggestResponse
	7, // 8: search.SearchService.GetHistory:output_type -> search.HistoryResponse
	9, // 9: search.SearchService.DeleteHistory:output_type -> search.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_search_search_proto_init() }
func file_proto_search_search_proto_init() {
	if File_proto_search_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_search_search_proto_rawDesc), len(file_proto_search_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_search_search_proto_goTypes,
		DependencyIndexes: file_proto_search_search_proto_depIdxs,
		MessageInfos:      file_proto_search_search_proto_msgTypes,
	}.Build()
	File_proto_search_search_proto = out.File
	file_proto_search_search_proto_goTypes = nil
	file_proto_search_search_proto_depIdxs = nil
}
