// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: comment/comment.proto

package comment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_comment_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{0}
}

type SimpleUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleUser) Reset() {
	*x = SimpleUser{}
	mi := &file_comment_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleUser) ProtoMessage() {}

func (x *SimpleUser) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleUser.ProtoReflect.Descriptor instead.
func (*SimpleUser) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{1}
}

func (x *SimpleUser) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SimpleUser) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *SimpleUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type ReplyUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyUser) Reset() {
	*x = ReplyUser{}
	mi := &file_comment_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyUser) ProtoMessage() {}

func (x *ReplyUser) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyUser.ProtoReflect.Descriptor instead.
func (*ReplyUser) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{2}
}

func (x *ReplyUser) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReplyUser) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type Comment struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PostId              string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId              int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserNickname        string                 `protobuf:"bytes,4,opt,name=user_nickname,json=userNickname,proto3" json:"user_nickname,omitempty"`
	UserAvatar          string                 `protobuf:"bytes,5,opt,name=user_avatar,json=userAvatar,proto3" json:"user_avatar,omitempty"`
	Content             string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	ParentId            string                 `protobuf:"bytes,7,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ReplyToUserId       int64                  `protobuf:"varint,8,opt,name=reply_to_user_id,json=replyToUserId,proto3" json:"reply_to_user_id,omitempty"`
	ReplyToUserNickname string                 `protobuf:"bytes,9,opt,name=reply_to_user_nickname,json=replyToUserNickname,proto3" json:"reply_to_user_nickname,omitempty"`
	ReplyCount          int32                  `protobuf:"varint,10,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`
	LikeCount           int32                  `protobuf:"varint,11,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	IsLiked             bool                   `protobuf:"varint,12,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	CreatedAt           int64                  `protobuf:"varint,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ChildComments       []*Comment             `protobuf:"bytes,14,rep,name=child_comments,json=childComments,proto3" json:"child_comments,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_comment_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{3}
}

func (x *Comment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Comment) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Comment) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Comment) GetUserNickname() string {
	if x != nil {
		return x.UserNickname
	}
	return ""
}

func (x *Comment) GetUserAvatar() string {
	if x != nil {
		return x.UserAvatar
	}
	return ""
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Comment) GetReplyToUserId() int64 {
	if x != nil {
		return x.ReplyToUserId
	}
	return 0
}

func (x *Comment) GetReplyToUserNickname() string {
	if x != nil {
		return x.ReplyToUserNickname
	}
	return ""
}

func (x *Comment) GetReplyCount() int32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *Comment) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Comment) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *Comment) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Comment) GetChildComments() []*Comment {
	if x != nil {
		return x.ChildComments
	}
	return nil
}

type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	CurrentUserId int64                  `protobuf:"varint,2,opt,name=current_user_id,json=currentUserId,proto3" json:"current_user_id,omitempty"`
	UserNickname  string                 `protobuf:"bytes,3,opt,name=user_nickname,json=userNickname,proto3" json:"user_nickname,omitempty"`
	UserAvatar    string                 `protobuf:"bytes,4,opt,name=user_avatar,json=userAvatar,proto3" json:"user_avatar,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	ParentId      string                 `protobuf:"bytes,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_comment_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCommentRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *CreateCommentRequest) GetCurrentUserId() int64 {
	if x != nil {
		return x.CurrentUserId
	}
	return 0
}

func (x *CreateCommentRequest) GetUserNickname() string {
	if x != nil {
		return x.UserNickname
	}
	return ""
}

func (x *CreateCommentRequest) GetUserAvatar() string {
	if x != nil {
		return x.UserAvatar
	}
	return ""
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateCommentRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type DeleteCommentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommentId       string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	CurrentUserId   int64                  `protobuf:"varint,2,opt,name=current_user_id,json=currentUserId,proto3" json:"current_user_id,omitempty"`
	CurrentUserRole string                 `protobuf:"bytes,3,opt,name=current_user_role,json=currentUserRole,proto3" json:"current_user_role,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_comment_comment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *DeleteCommentRequest) GetCurrentUserId() int64 {
	if x != nil {
		return x.CurrentUserId
	}
	return 0
}

func (x *DeleteCommentRequest) GetCurrentUserRole() string {
	if x != nil {
		return x.CurrentUserRole
	}
	return ""
}

type ListRootCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	CurrentUserId int64                  `protobuf:"varint,4,opt,name=current_user_id,json=currentUserId,proto3" json:"current_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRootCommentsRequest) Reset() {
	*x = ListRootCommentsRequest{}
	mi := &file_comment_comment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRootCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRootCommentsRequest) ProtoMessage() {}

func (x *ListRootCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRootCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListRootCommentsRequest) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{6}
}

func (x *ListRootCommentsRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *ListRootCommentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRootCommentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRootCommentsRequest) GetCurrentUserId() int64 {
	if x != nil {
		return x.CurrentUserId
	}
	return 0
}

type ListSubCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootCommentId string                 `protobuf:"bytes,1,opt,name=root_comment_id,json=rootCommentId,proto3" json:"root_comment_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	CurrentUserId int64                  `protobuf:"varint,4,opt,name=current_user_id,json=currentUserId,proto3" json:"current_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubCommentsRequest) Reset() {
	*x = ListSubCommentsRequest{}
	mi := &file_comment_comment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubCommentsRequest) ProtoMessage() {}

func (x *ListSubCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListSubCommentsRequest) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{7}
}

func (x *ListSubCommentsRequest) GetRootCommentId() string {
	if x != nil {
		return x.RootCommentId
	}
	return ""
}

func (x *ListSubCommentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSubCommentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSubCommentsRequest) GetCurrentUserId() int64 {
	if x != nil {
		return x.CurrentUserId
	}
	return 0
}

type CommentPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Comment             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentPageResponse) Reset() {
	*x = CommentPageResponse{}
	mi := &file_comment_comment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentPageResponse) ProtoMessage() {}

func (x *CommentPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_comment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentPageResponse.ProtoReflect.Descriptor instead.
func (*CommentPageResponse) Descriptor() ([]byte, []int) {
	return file_comment_comment_proto_rawDescGZIP(), []int{8}
}

func (x *CommentPageResponse) GetItems() []*Comment {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CommentPageResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CommentPageResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CommentPageResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_comment_comment_proto protoreflect.FileDescriptor

const file_comment_comment_proto_rawDesc = "" +
	"\n" +
	"\x15comment/comment.proto\x12\acomment\"\a\n" +
	"\x05Empty\"Y\n" +
	"\n" +
	"SimpleUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"@\n" +
	"\tReplyUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\"\xd9\x03\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12#\n" +
	"\ruser_nickname\x18\x04 \x01(\tR\fuserNickname\x12\x1f\n" +
	"\vuser_avatar\x18\x05 \x01(\tR\n" +
	"userAvatar\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\a \x01(\tR\bparentId\x12'\n" +
	"\x10reply_to_user_id\x18\b \x01(\x03R\rreplyToUserId\x123\n" +
	"\x16reply_to_user_nickname\x18\t \x01(\tR\x13replyToUserNickname\x12\x1f\n" +
	"\vreply_count\x18\n" +
	" \x01(\x05R\n" +
	"replyCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\v \x01(\x05R\tlikeCount\x12\x19\n" +
	"\bis_liked\x18\f \x01(\bR\aisLiked\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\x03R\tcreatedAt\x127\n" +
	"\x0echild_comments\x18\x0e \x03(\v2\x10.comment.CommentR\rchildComments\"\xd4\x01\n" +
	"\x14CreateCommentRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12&\n" +
	"\x0fcurrent_user_id\x18\x02 \x01(\x03R\rcurrentUserId\x12#\n" +
	"\ruser_nickname\x18\x03 \x01(\tR\fuserNickname\x12\x1f\n" +
	"\vuser_avatar\x18\x04 \x01(\tR\n" +
	"userAvatar\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x06 \x01(\tR\bparentId\"\x89\x01\n" +
	"\x14DeleteCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\x12&\n" +
	"\x0fcurrent_user_id\x18\x02 \x01(\x03R\rcurrentUserId\x12*\n" +
	"\x11current_user_role\x18\x03 \x01(\tR\x0fcurrentUserRole\"\x8b\x01\n" +
	"\x17ListRootCommentsRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12&\n" +
	"\x0fcurrent_user_id\x18\x04 \x01(\x03R\rcurrentUserId\"\x99\x01\n" +
	"\x16ListSubCommentsRequest\x12&\n" +
	"\x0froot_comment_id\x18\x01 \x01(\tR\rrootCommentId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12&\n" +
	"\x0fcurrent_user_id\x18\x04 \x01(\x03R\rcurrentUserId\"\x84\x01\n" +
	"\x13CommentPageResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.comment.CommentR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize2\xb8\x02\n" +
	"\x0eCommentService\x12@\n" +
	"\rCreateComment\x12\x1d.comment.CreateCommentRequest\x1a\x10.comment.Comment\x12>\n" +
	"\rDeleteComment\x12\x1d.comment.DeleteCommentRequest\x1a\x0e.comment.Empty\x12R\n" +
	"\x10ListRootComments\x12 .comment.ListRootCommentsRequest\x1a\x1c.comment.CommentPageResponse\x12P\n" +
	"\x0fListSubComments\x12\x1f.comment.ListSubCommentsRequest\x1a\x1c.comment.CommentPageResponseB\vZ\t./commentb\x06proto3"

var (
	file_comment_comment_proto_rawDescOnce sync.Once
	file_comment_comment_proto_rawDescData []byte
)

func file_comment_comment_proto_rawDescGZIP() []byte {
	file_comment_comment_proto_rawDescOnce.Do(func() {
		file_comment_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comment_comment_proto_rawDesc), len(file_comment_comment_proto_rawDesc)))
	})
	return file_comment_comment_proto_rawDescData
}

var file_comment_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_comment_comment_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: comment.Empty
	(*SimpleUser)(nil),              // 1: comment.SimpleUser
	(*ReplyUser)(nil),               // 2: comment.ReplyUser
	(*Comment)(nil),                 // 3: comment.Comment
	(*CreateCommentRequest)(nil),    // 4: comment.CreateCommentRequest
	(*DeleteCommentRequest)(nil),    // 5: comment.DeleteCommentRequest
	(*ListRootCommentsRequest)(nil), // 6: comment.ListRootCommentsRequest
	(*ListSubCommentsRequest)(nil),  // 7: comment.ListSubCommentsRequest
	(*CommentPageResponse)(nil),     // 8: comment.CommentPageResponse
}
var file_comment_comment_proto_depIdxs = []int32{
	3, // 0: comment.Comment.child_comments:type_name -> comment.Comment
	3, // 1: comment.CommentPageResponse.items:type_name -> comment.Comment
	4, // 2: comment.CommentService.CreateComment:input_type -> comment.CreateCommentRequest
	5, // 3: comment.CommentService.DeleteComment:input_type -> comment.DeleteCommentRequest
	6, // 4: comment.CommentService.ListRootComments:input_type -> comment.ListRootCommentsRequest
	7, // 5: comment.CommentService.ListSubComments:input_type -> comment.ListSubCommentsRequest
	3, // 6: comment.CommentService.CreateComment:output_type -> comment.Comment
	0, // 7: comment.CommentService.DeleteComment:output_type -> comment.Empty
	8, // 8: comment.CommentService.ListRootComments:output_type -> comment.CommentPageResponse
	8, // 9: comment.CommentService.ListSubComments:output_type -> comment.CommentPageResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_comment_comment_proto_init() }
func file_comment_comment_proto_init() {
	if File_comment_comment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comment_comment_proto_rawDesc), len(file_comment_comment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comment_comment_proto_goTypes,
		DependencyIndexes: file_comment_comment_proto_depIdxs,
		MessageInfos:      file_comment_comment_proto_msgTypes,
	}.Build()
	File_comment_comment_proto = out.File
	file_comment_comment_proto_goTypes = nil
	file_comment_comment_proto_depIdxs = nil
}
