// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: interaction.proto

package interactionservice

import (
	"context"

	"interaction-rpc/interaction"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty                  = interaction.Empty
	InteractionRequest     = interaction.InteractionRequest
	RateRequest            = interaction.RateRequest
	BatchPostStatsRequest  = interaction.BatchPostStatsRequest
	BatchPostStatsResponse = interaction.BatchPostStatsResponse
	PostStats              = interaction.PostStats
	UserStatsRequest       = interaction.UserStatsRequest
	UserStatsResponse      = interaction.UserStatsResponse

	InteractionService interface {
		// 点赞帖子
		LikePost(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error)
		// 取消点赞帖子
		UnlikePost(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error)
		// 收藏帖子
		CollectPost(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error)
		// 取消收藏帖子
		UncollectPost(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error)
		// 评分帖子
		RatePost(ctx context.Context, in *RateRequest, opts ...grpc.CallOption) (*Empty, error)
		// 点赞评论
		LikeComment(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error)
		// 取消点赞评论
		UnlikeComment(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error)
		// 批量查询帖子互动状态
		BatchPostStats(ctx context.Context, in *BatchPostStatsRequest, opts ...grpc.CallOption) (*BatchPostStatsResponse, error)
		// 用户主页聚合数据
		GetUserStats(ctx context.Context, in *UserStatsRequest, opts ...grpc.CallOption) (*UserStatsResponse, error)
	}

	defaultInteractionService struct {
		cli zrpc.Client
	}
)

func NewInteractionService(cli zrpc.Client) InteractionService {
	return &defaultInteractionService{
		cli: cli,
	}
}

// 点赞帖子
func (m *defaultInteractionService) LikePost(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := interaction.NewInteractionServiceClient(m.cli.Conn())
	return client.LikePost(ctx, in, opts...)
}

// 取消点赞帖子
func (m *defaultInteractionService) UnlikePost(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := interaction.NewInteractionServiceClient(m.cli.Conn())
	return client.UnlikePost(ctx, in, opts...)
}

// 收藏帖子
func (m *defaultInteractionService) CollectPost(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := interaction.NewInteractionServiceClient(m.cli.Conn())
	return client.CollectPost(ctx, in, opts...)
}

// 取消收藏帖子
func (m *defaultInteractionService) UncollectPost(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := interaction.NewInteractionServiceClient(m.cli.Conn())
	return client.UncollectPost(ctx, in, opts...)
}

// 评分帖子
func (m *defaultInteractionService) RatePost(ctx context.Context, in *RateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := interaction.NewInteractionServiceClient(m.cli.Conn())
	return client.RatePost(ctx, in, opts...)
}

// 点赞评论
func (m *defaultInteractionService) LikeComment(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := interaction.NewInteractionServiceClient(m.cli.Conn())
	return client.LikeComment(ctx, in, opts...)
}

// 取消点赞评论
func (m *defaultInteractionService) UnlikeComment(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := interaction.NewInteractionServiceClient(m.cli.Conn())
	return client.UnlikeComment(ctx, in, opts...)
}

// 批量查询帖子互动状态
func (m *defaultInteractionService) BatchPostStats(ctx context.Context, in *BatchPostStatsRequest, opts ...grpc.CallOption) (*BatchPostStatsResponse, error) {
	client := interaction.NewInteractionServiceClient(m.cli.Conn())
	return client.BatchPostStats(ctx, in, opts...)
}

// 用户主页聚合数据
func (m *defaultInteractionService) GetUserStats(ctx context.Context, in *UserStatsRequest, opts ...grpc.CallOption) (*UserStatsResponse, error) {
	client := interaction.NewInteractionServiceClient(m.cli.Conn())
	return client.GetUserStats(ctx, in, opts...)
}
