// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: interaction.proto

package server

import (
	"context"

	"interaction-rpc/interaction"
	"interaction-rpc/internal/logic"
	"interaction-rpc/internal/svc"
)

type InteractionServiceServer struct {
	svcCtx *svc.ServiceContext
	interaction.UnimplementedInteractionServiceServer
}

func NewInteractionServiceServer(svcCtx *svc.ServiceContext) *InteractionServiceServer {
	return &InteractionServiceServer{
		svcCtx: svcCtx,
	}
}

// 点赞帖子
func (s *InteractionServiceServer) LikePost(ctx context.Context, in *interaction.InteractionRequest) (*interaction.Empty, error) {
	l := logic.NewLikePostLogic(ctx, s.svcCtx)
	return l.LikePost(in)
}

// 取消点赞帖子
func (s *InteractionServiceServer) UnlikePost(ctx context.Context, in *interaction.InteractionRequest) (*interaction.Empty, error) {
	l := logic.NewUnlikePostLogic(ctx, s.svcCtx)
	return l.UnlikePost(in)
}

// 收藏帖子
func (s *InteractionServiceServer) CollectPost(ctx context.Context, in *interaction.InteractionRequest) (*interaction.Empty, error) {
	l := logic.NewCollectPostLogic(ctx, s.svcCtx)
	return l.CollectPost(in)
}

// 取消收藏帖子
func (s *InteractionServiceServer) UncollectPost(ctx context.Context, in *interaction.InteractionRequest) (*interaction.Empty, error) {
	l := logic.NewUncollectPostLogic(ctx, s.svcCtx)
	return l.UncollectPost(in)
}

// 评分帖子
func (s *InteractionServiceServer) RatePost(ctx context.Context, in *interaction.RateRequest) (*interaction.Empty, error) {
	l := logic.NewRatePostLogic(ctx, s.svcCtx)
	return l.RatePost(in)
}

// 点赞评论
func (s *InteractionServiceServer) LikeComment(ctx context.Context, in *interaction.InteractionRequest) (*interaction.Empty, error) {
	l := logic.NewLikeCommentLogic(ctx, s.svcCtx)
	return l.LikeComment(in)
}

// 取消点赞评论
func (s *InteractionServiceServer) UnlikeComment(ctx context.Context, in *interaction.InteractionRequest) (*interaction.Empty, error) {
	l := logic.NewUnlikeCommentLogic(ctx, s.svcCtx)
	return l.UnlikeComment(in)
}
