// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: search.proto

package searchservice

import (
	"context"

	"search-rpc/search"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ClearHistoryRequest = search.ClearHistoryRequest
	Empty               = search.Empty
	HistoryRequest      = search.HistoryRequest
	HistoryResponse     = search.HistoryResponse
	SearchPostVO        = search.SearchPostVO
	SearchRequest       = search.SearchRequest
	SearchResponse      = search.SearchResponse
	SuggestRequest      = search.SuggestRequest
	SuggestResponse     = search.SuggestResponse
	UserVO              = search.UserVO

	SearchService interface {
		// 核心搜索 (对应 Java: searchPosts)
		Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
		// 搜索补全 (对应 Java: getSearchSuggestions)
		Suggest(ctx context.Context, in *SuggestRequest, opts ...grpc.CallOption) (*SuggestResponse, error)
		// 获取搜索历史 (对应 Java: getSearchHistory)
		GetHistory(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error)
		// 删除搜索历史 (对应 Java: clearSearchHistory / deleteSearchHistoryItem)
		DeleteHistory(ctx context.Context, in *ClearHistoryRequest, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultSearchService struct {
		cli zrpc.Client
	}
)

func NewSearchService(cli zrpc.Client) SearchService {
	return &defaultSearchService{
		cli: cli,
	}
}

// 核心搜索 (对应 Java: searchPosts)
func (m *defaultSearchService) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	client := search.NewSearchServiceClient(m.cli.Conn())
	return client.Search(ctx, in, opts...)
}

// 搜索补全 (对应 Java: getSearchSuggestions)
func (m *defaultSearchService) Suggest(ctx context.Context, in *SuggestRequest, opts ...grpc.CallOption) (*SuggestResponse, error) {
	client := search.NewSearchServiceClient(m.cli.Conn())
	return client.Suggest(ctx, in, opts...)
}

// 获取搜索历史 (对应 Java: getSearchHistory)
func (m *defaultSearchService) GetHistory(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error) {
	client := search.NewSearchServiceClient(m.cli.Conn())
	return client.GetHistory(ctx, in, opts...)
}

// 删除搜索历史 (对应 Java: clearSearchHistory / deleteSearchHistoryItem)
func (m *defaultSearchService) DeleteHistory(ctx context.Context, in *ClearHistoryRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := search.NewSearchServiceClient(m.cli.Conn())
	return client.DeleteHistory(ctx, in, opts...)
}
