global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'platform-java'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'gateway-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['gateway-api:40090']

  - job_name: 'interaction-rpc'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['interaction-rpc:40092']

  - job_name: 'user-rpc'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['user-rpc:40091']

  - job_name: 'search-rpc'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['search-rpc:40093']

  - job_name: 'notification-rpc'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['notification-rpc:40095']

  - job_name: 'comment-rpc'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['comment-rpc:40096']
