// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package userservice

import (
	"context"

	"user-rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AuthResponse            = user.AuthResponse
	BatchGetUsersRequest    = user.BatchGetUsersRequest
	BatchGetUsersResponse   = user.BatchGetUsersResponse
	BindEmailRequest        = user.BindEmailRequest
	ChangePasswordRequest   = user.ChangePasswordRequest
	AdminDeleteUserRequest  = user.AdminDeleteUserRequest
	DeleteUserRequest       = user.DeleteUserRequest
	Empty                   = user.Empty
	GetMyProfileRequest     = user.GetMyProfileRequest
	GetPublicProfileRequest = user.GetPublicProfileRequest
	GetUserSummaryRequest   = user.GetUserSummaryRequest
	LoginRequest            = user.LoginRequest
	LogoutRequest           = user.LogoutRequest
	PublicUserProfile       = user.PublicUserProfile
	RefreshTokenRequest     = user.RefreshTokenRequest
	RegisterRequest         = user.RegisterRequest
	ResetPasswordRequest    = user.ResetPasswordRequest
	SendEmailCodeRequest    = user.SendEmailCodeRequest
	SendEmailCodeResponse   = user.SendEmailCodeResponse
	TokenPair               = user.TokenPair
	UpdateProfileRequest    = user.UpdateProfileRequest
	UpdateUserStatusRequest = user.UpdateUserStatusRequest
	UserProfile             = user.UserProfile
	UserSummary             = user.UserSummary
	VerifyEmailCodeRequest  = user.VerifyEmailCodeRequest
	VerifyEmailCodeResponse = user.VerifyEmailCodeResponse

	UserService interface {
		// Auth / Account
		SendEmailCode(ctx context.Context, in *SendEmailCodeRequest, opts ...grpc.CallOption) (*SendEmailCodeResponse, error)
		VerifyEmailCode(ctx context.Context, in *VerifyEmailCodeRequest, opts ...grpc.CallOption) (*VerifyEmailCodeResponse, error)
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error)
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error)
		RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*AuthResponse, error)
		Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*Empty, error)
		ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*Empty, error)
		ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*Empty, error)
		BindEmail(ctx context.Context, in *BindEmailRequest, opts ...grpc.CallOption) (*Empty, error)
		// Profile
		GetMyProfile(ctx context.Context, in *GetMyProfileRequest, opts ...grpc.CallOption) (*UserProfile, error)
		GetPublicProfile(ctx context.Context, in *GetPublicProfileRequest, opts ...grpc.CallOption) (*PublicUserProfile, error)
		UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UserProfile, error)
		UpdateUserStatus(ctx context.Context, in *UpdateUserStatusRequest, opts ...grpc.CallOption) (*Empty, error)
		DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*Empty, error)
		AdminDeleteUser(ctx context.Context, in *AdminDeleteUserRequest, opts ...grpc.CallOption) (*Empty, error)
		// Cross-service
		GetUserSummary(ctx context.Context, in *GetUserSummaryRequest, opts ...grpc.CallOption) (*UserSummary, error)
		BatchGetUsers(ctx context.Context, in *BatchGetUsersRequest, opts ...grpc.CallOption) (*BatchGetUsersResponse, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

// Auth / Account
func (m *defaultUserService) SendEmailCode(ctx context.Context, in *SendEmailCodeRequest, opts ...grpc.CallOption) (*SendEmailCodeResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.SendEmailCode(ctx, in, opts...)
}

func (m *defaultUserService) VerifyEmailCode(ctx context.Context, in *VerifyEmailCodeRequest, opts ...grpc.CallOption) (*VerifyEmailCodeResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.VerifyEmailCode(ctx, in, opts...)
}

func (m *defaultUserService) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUserService) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUserService) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

func (m *defaultUserService) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

func (m *defaultUserService) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.ResetPassword(ctx, in, opts...)
}

func (m *defaultUserService) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.ChangePassword(ctx, in, opts...)
}

func (m *defaultUserService) BindEmail(ctx context.Context, in *BindEmailRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.BindEmail(ctx, in, opts...)
}

// Profile
func (m *defaultUserService) GetMyProfile(ctx context.Context, in *GetMyProfileRequest, opts ...grpc.CallOption) (*UserProfile, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.GetMyProfile(ctx, in, opts...)
}

func (m *defaultUserService) GetPublicProfile(ctx context.Context, in *GetPublicProfileRequest, opts ...grpc.CallOption) (*PublicUserProfile, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.GetPublicProfile(ctx, in, opts...)
}

func (m *defaultUserService) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UserProfile, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.UpdateProfile(ctx, in, opts...)
}

func (m *defaultUserService) UpdateUserStatus(ctx context.Context, in *UpdateUserStatusRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserStatus(ctx, in, opts...)
}

func (m *defaultUserService) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}

func (m *defaultUserService) AdminDeleteUser(ctx context.Context, in *AdminDeleteUserRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.AdminDeleteUser(ctx, in, opts...)
}

// Cross-service
func (m *defaultUserService) GetUserSummary(ctx context.Context, in *GetUserSummaryRequest, opts ...grpc.CallOption) (*UserSummary, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.GetUserSummary(ctx, in, opts...)
}

func (m *defaultUserService) BatchGetUsers(ctx context.Context, in *BatchGetUsersRequest, opts ...grpc.CallOption) (*BatchGetUsersResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.BatchGetUsers(ctx, in, opts...)
}
