// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: notification.proto

package server

import (
	"context"

	"notification-rpc/internal/logic"
	"notification-rpc/internal/svc"
	"notification-rpc/notification"
)

type NotificationServiceServer struct {
	svcCtx *svc.ServiceContext
	notification.UnimplementedNotificationServiceServer
}

func NewNotificationServiceServer(svcCtx *svc.ServiceContext) *NotificationServiceServer {
	return &NotificationServiceServer{
		svcCtx: svcCtx,
	}
}

// server 层本身不承载复杂业务，只负责：
// 1. 承接 gRPC 请求
// 2. 根据方法名路由到对应 logic
// 3. 保持 serviceContext 依赖注入风格统一

// 对应当前 /api/message/unread-count
func (s *NotificationServiceServer) GetUnreadCount(ctx context.Context, in *notification.GetUnreadCountRequest) (*notification.GetUnreadCountResponse, error) {
	l := logic.NewGetUnreadCountLogic(ctx, s.svcCtx)
	return l.GetUnreadCount(in)
}

// 对应当前 /api/message/notifications
func (s *NotificationServiceServer) ListNotifications(ctx context.Context, in *notification.ListNotificationsRequest) (*notification.ListNotificationsResponse, error) {
	l := logic.NewListNotificationsLogic(ctx, s.svcCtx)
	return l.ListNotifications(in)
}

// 对应当前 /api/message/read (全部已读)
func (s *NotificationServiceServer) MarkAllRead(ctx context.Context, in *notification.MarkAllReadRequest) (*notification.Empty, error) {
	l := logic.NewMarkAllReadLogic(ctx, s.svcCtx)
	return l.MarkAllRead(in)
}

// 对应当前 /api/message/read (批量已读)
func (s *NotificationServiceServer) MarkBatchRead(ctx context.Context, in *notification.MarkBatchReadRequest) (*notification.Empty, error) {
	l := logic.NewMarkBatchReadLogic(ctx, s.svcCtx)
	return l.MarkBatchRead(in)
}

// 普通插入：评论、回复、系统类通知
func (s *NotificationServiceServer) CreateNotification(ctx context.Context, in *notification.CreateNotificationRequest) (*notification.Empty, error) {
	l := logic.NewCreateNotificationLogic(ctx, s.svcCtx)
	return l.CreateNotification(in)
}

// 去重 upsert：点赞、收藏、评分、关注类通知
func (s *NotificationServiceServer) UpsertNotification(ctx context.Context, in *notification.UpsertNotificationRequest) (*notification.Empty, error) {
	l := logic.NewUpsertNotificationLogic(ctx, s.svcCtx)
	return l.UpsertNotification(in)
}

// 仅供管理/数据修复使用，便于迁移旧数据时执行一次清洗。
func (s *NotificationServiceServer) CleanDuplicateNotifications(ctx context.Context, in *notification.CleanDuplicateNotificationsRequest) (*notification.CleanDuplicateNotificationsResponse, error) {
	l := logic.NewCleanDuplicateNotificationsLogic(ctx, s.svcCtx)
	return l.CleanDuplicateNotifications(in)
}
