// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"user-rpc/internal/logic"
	"user-rpc/internal/svc"
	"user-rpc/user"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

// Auth / Account
func (s *UserServiceServer) SendEmailCode(ctx context.Context, in *user.SendEmailCodeRequest) (*user.SendEmailCodeResponse, error) {
	l := logic.NewSendEmailCodeLogic(ctx, s.svcCtx)
	return l.SendEmailCode(in)
}

func (s *UserServiceServer) VerifyEmailCode(ctx context.Context, in *user.VerifyEmailCodeRequest) (*user.VerifyEmailCodeResponse, error) {
	l := logic.NewVerifyEmailCodeLogic(ctx, s.svcCtx)
	return l.VerifyEmailCode(in)
}

func (s *UserServiceServer) Register(ctx context.Context, in *user.RegisterRequest) (*user.AuthResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServiceServer) Login(ctx context.Context, in *user.LoginRequest) (*user.AuthResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServiceServer) RefreshToken(ctx context.Context, in *user.RefreshTokenRequest) (*user.AuthResponse, error) {
	l := logic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

func (s *UserServiceServer) Logout(ctx context.Context, in *user.LogoutRequest) (*user.Empty, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

func (s *UserServiceServer) ResetPassword(ctx context.Context, in *user.ResetPasswordRequest) (*user.Empty, error) {
	l := logic.NewResetPasswordLogic(ctx, s.svcCtx)
	return l.ResetPassword(in)
}

func (s *UserServiceServer) ChangePassword(ctx context.Context, in *user.ChangePasswordRequest) (*user.Empty, error) {
	l := logic.NewChangePasswordLogic(ctx, s.svcCtx)
	return l.ChangePassword(in)
}

func (s *UserServiceServer) BindEmail(ctx context.Context, in *user.BindEmailRequest) (*user.Empty, error) {
	l := logic.NewBindEmailLogic(ctx, s.svcCtx)
	return l.BindEmail(in)
}

// Profile
func (s *UserServiceServer) GetMyProfile(ctx context.Context, in *user.GetMyProfileRequest) (*user.UserProfile, error) {
	l := logic.NewGetMyProfileLogic(ctx, s.svcCtx)
	return l.GetMyProfile(in)
}

func (s *UserServiceServer) GetPublicProfile(ctx context.Context, in *user.GetPublicProfileRequest) (*user.PublicUserProfile, error) {
	l := logic.NewGetPublicProfileLogic(ctx, s.svcCtx)
	return l.GetPublicProfile(in)
}

func (s *UserServiceServer) UpdateProfile(ctx context.Context, in *user.UpdateProfileRequest) (*user.UserProfile, error) {
	l := logic.NewUpdateProfileLogic(ctx, s.svcCtx)
	return l.UpdateProfile(in)
}

func (s *UserServiceServer) UpdateUserStatus(ctx context.Context, in *user.UpdateUserStatusRequest) (*user.Empty, error) {
	l := logic.NewUpdateUserStatusLogic(ctx, s.svcCtx)
	return l.UpdateUserStatus(in)
}

// Cross-service
func (s *UserServiceServer) GetUserSummary(ctx context.Context, in *user.GetUserSummaryRequest) (*user.UserSummary, error) {
	l := logic.NewGetUserSummaryLogic(ctx, s.svcCtx)
	return l.GetUserSummary(in)
}

func (s *UserServiceServer) BatchGetUsers(ctx context.Context, in *user.BatchGetUsersRequest) (*user.BatchGetUsersResponse, error) {
	l := logic.NewBatchGetUsersLogic(ctx, s.svcCtx)
	return l.BatchGetUsers(in)
}
