// 声明使用 proto3 语法版本 (目前的主流版本，默认字段可选)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/interaction/interaction.proto

// 定义包名，类似于 Java 的 package com.szu...

package interaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用的空响应
// 对应 Java Result<Void>，gRPC 必须有返回类型，哪怕是空的
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_interaction_interaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interaction_interaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_interaction_interaction_proto_rawDescGZIP(), []int{0}
}

// 针对“目标”的互动请求
// 适用于：点赞帖子/评论、取消点赞、收藏/取消收藏
// Java 对应: PostIdDTO 或 CommentIdDTO + UserContext.getUserId()
type InteractionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`      // 发起互动的用户ID (Java中从Token解析，RPC需显式传递)
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 目标ID (PostId 或 CommentId)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractionRequest) Reset() {
	*x = InteractionRequest{}
	mi := &file_proto_interaction_interaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionRequest) ProtoMessage() {}

func (x *InteractionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interaction_interaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionRequest.ProtoReflect.Descriptor instead.
func (*InteractionRequest) Descriptor() ([]byte, []int) {
	return file_proto_interaction_interaction_proto_rawDescGZIP(), []int{1}
}

func (x *InteractionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *InteractionRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

// 评分请求
// Java 对应: PostRateDTO
type RateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`      // 用户ID
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // PostId
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`                     // 分数 (Java Double 对应 proto double)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateRequest) Reset() {
	*x = RateRequest{}
	mi := &file_proto_interaction_interaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateRequest) ProtoMessage() {}

func (x *RateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interaction_interaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateRequest.ProtoReflect.Descriptor instead.
func (*RateRequest) Descriptor() ([]byte, []int) {
	return file_proto_interaction_interaction_proto_rawDescGZIP(), []int{2}
}

func (x *RateRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RateRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *RateRequest) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_proto_interaction_interaction_proto protoreflect.FileDescriptor

const file_proto_interaction_interaction_proto_rawDesc = "" +
	"\n" +
	"#proto/interaction/interaction.proto\x12\vinteraction\"\a\n" +
	"\x05Empty\"J\n" +
	"\x12InteractionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\"Y\n" +
	"\vRateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score2\xe6\x03\n" +
	"\x12InteractionService\x12?\n" +
	"\bLikePost\x12\x1f.interaction.InteractionRequest\x1a\x12.interaction.Empty\x12A\n" +
	"\n" +
	"UnlikePost\x12\x1f.interaction.InteractionRequest\x1a\x12.interaction.Empty\x12B\n" +
	"\vCollectPost\x12\x1f.interaction.InteractionRequest\x1a\x12.interaction.Empty\x12D\n" +
	"\rUncollectPost\x12\x1f.interaction.InteractionRequest\x1a\x12.interaction.Empty\x128\n" +
	"\bRatePost\x12\x18.interaction.RateRequest\x1a\x12.interaction.Empty\x12B\n" +
	"\vLikeComment\x12\x1f.interaction.InteractionRequest\x1a\x12.interaction.Empty\x12D\n" +
	"\rUnlikeComment\x12\x1f.interaction.InteractionRequest\x1a\x12.interaction.EmptyB\x0fZ\r./interactionb\x06proto3"

var (
	file_proto_interaction_interaction_proto_rawDescOnce sync.Once
	file_proto_interaction_interaction_proto_rawDescData []byte
)

func file_proto_interaction_interaction_proto_rawDescGZIP() []byte {
	file_proto_interaction_interaction_proto_rawDescOnce.Do(func() {
		file_proto_interaction_interaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_interaction_interaction_proto_rawDesc), len(file_proto_interaction_interaction_proto_rawDesc)))
	})
	return file_proto_interaction_interaction_proto_rawDescData
}

var file_proto_interaction_interaction_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_interaction_interaction_proto_goTypes = []any{
	(*Empty)(nil),              // 0: interaction.Empty
	(*InteractionRequest)(nil), // 1: interaction.InteractionRequest
	(*RateRequest)(nil),        // 2: interaction.RateRequest
}
var file_proto_interaction_interaction_proto_depIdxs = []int32{
	1, // 0: interaction.InteractionService.LikePost:input_type -> interaction.InteractionRequest
	1, // 1: interaction.InteractionService.UnlikePost:input_type -> interaction.InteractionRequest
	1, // 2: interaction.InteractionService.CollectPost:input_type -> interaction.InteractionRequest
	1, // 3: interaction.InteractionService.UncollectPost:input_type -> interaction.InteractionRequest
	2, // 4: interaction.InteractionService.RatePost:input_type -> interaction.RateRequest
	1, // 5: interaction.InteractionService.LikeComment:input_type -> interaction.InteractionRequest
	1, // 6: interaction.InteractionService.UnlikeComment:input_type -> interaction.InteractionRequest
	0, // 7: interaction.InteractionService.LikePost:output_type -> interaction.Empty
	0, // 8: interaction.InteractionService.UnlikePost:output_type -> interaction.Empty
	0, // 9: interaction.InteractionService.CollectPost:output_type -> interaction.Empty
	0, // 10: interaction.InteractionService.UncollectPost:output_type -> interaction.Empty
	0, // 11: interaction.InteractionService.RatePost:output_type -> interaction.Empty
	0, // 12: interaction.InteractionService.LikeComment:output_type -> interaction.Empty
	0, // 13: interaction.InteractionService.UnlikeComment:output_type -> interaction.Empty
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_interaction_interaction_proto_init() }
func file_proto_interaction_interaction_proto_init() {
	if File_proto_interaction_interaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_interaction_interaction_proto_rawDesc), len(file_proto_interaction_interaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_interaction_interaction_proto_goTypes,
		DependencyIndexes: file_proto_interaction_interaction_proto_depIdxs,
		MessageInfos:      file_proto_interaction_interaction_proto_msgTypes,
	}.Build()
	File_proto_interaction_interaction_proto = out.File
	file_proto_interaction_interaction_proto_goTypes = nil
	file_proto_interaction_interaction_proto_depIdxs = nil
}
