// 声明使用 proto3 语法版本 (目前的主流版本，默认字段可选)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/interaction/interaction.proto

// 定义包名，类似于 Java 的 package com.szu...

package interaction

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InteractionService_LikePost_FullMethodName      = "/interaction.InteractionService/LikePost"
	InteractionService_UnlikePost_FullMethodName    = "/interaction.InteractionService/UnlikePost"
	InteractionService_CollectPost_FullMethodName   = "/interaction.InteractionService/CollectPost"
	InteractionService_UncollectPost_FullMethodName = "/interaction.InteractionService/UncollectPost"
	InteractionService_RatePost_FullMethodName      = "/interaction.InteractionService/RatePost"
	InteractionService_LikeComment_FullMethodName   = "/interaction.InteractionService/LikeComment"
	InteractionService_UnlikeComment_FullMethodName = "/interaction.InteractionService/UnlikeComment"
)

// InteractionServiceClient is the client API for InteractionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InteractionServiceClient interface {
	// 点赞帖子
	// 对应 Java: likePost(PostIdDTO)
	LikePost(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error)
	// 取消点赞帖子
	// 对应 Java: unlikePost(PostIdDTO)
	UnlikePost(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error)
	// 收藏帖子
	// 对应 Java: collectPost(PostIdDTO)
	CollectPost(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error)
	// 取消收藏帖子
	// 对应 Java: uncollectPost(PostIdDTO)
	UncollectPost(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error)
	// 评分帖子
	// 对应 Java: ratePost(PostRateDTO)
	RatePost(ctx context.Context, in *RateRequest, opts ...grpc.CallOption) (*Empty, error)
	// 点赞评论
	// 对应 Java: likeComment(CommentIdDTO)
	LikeComment(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error)
	// 取消点赞评论
	// 对应 Java: unlikeComment(CommentIdDTO)
	UnlikeComment(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error)
}

type interactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInteractionServiceClient(cc grpc.ClientConnInterface) InteractionServiceClient {
	return &interactionServiceClient{cc}
}

func (c *interactionServiceClient) LikePost(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, InteractionService_LikePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) UnlikePost(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, InteractionService_UnlikePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) CollectPost(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, InteractionService_CollectPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) UncollectPost(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, InteractionService_UncollectPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) RatePost(ctx context.Context, in *RateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, InteractionService_RatePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) LikeComment(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, InteractionService_LikeComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) UnlikeComment(ctx context.Context, in *InteractionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, InteractionService_UnlikeComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InteractionServiceServer is the server API for InteractionService service.
// All implementations must embed UnimplementedInteractionServiceServer
// for forward compatibility.
type InteractionServiceServer interface {
	// 点赞帖子
	// 对应 Java: likePost(PostIdDTO)
	LikePost(context.Context, *InteractionRequest) (*Empty, error)
	// 取消点赞帖子
	// 对应 Java: unlikePost(PostIdDTO)
	UnlikePost(context.Context, *InteractionRequest) (*Empty, error)
	// 收藏帖子
	// 对应 Java: collectPost(PostIdDTO)
	CollectPost(context.Context, *InteractionRequest) (*Empty, error)
	// 取消收藏帖子
	// 对应 Java: uncollectPost(PostIdDTO)
	UncollectPost(context.Context, *InteractionRequest) (*Empty, error)
	// 评分帖子
	// 对应 Java: ratePost(PostRateDTO)
	RatePost(context.Context, *RateRequest) (*Empty, error)
	// 点赞评论
	// 对应 Java: likeComment(CommentIdDTO)
	LikeComment(context.Context, *InteractionRequest) (*Empty, error)
	// 取消点赞评论
	// 对应 Java: unlikeComment(CommentIdDTO)
	UnlikeComment(context.Context, *InteractionRequest) (*Empty, error)
	mustEmbedUnimplementedInteractionServiceServer()
}

// UnimplementedInteractionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInteractionServiceServer struct{}

func (UnimplementedInteractionServiceServer) LikePost(context.Context, *InteractionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LikePost not implemented")
}
func (UnimplementedInteractionServiceServer) UnlikePost(context.Context, *InteractionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlikePost not implemented")
}
func (UnimplementedInteractionServiceServer) CollectPost(context.Context, *InteractionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectPost not implemented")
}
func (UnimplementedInteractionServiceServer) UncollectPost(context.Context, *InteractionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UncollectPost not implemented")
}
func (UnimplementedInteractionServiceServer) RatePost(context.Context, *RateRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RatePost not implemented")
}
func (UnimplementedInteractionServiceServer) LikeComment(context.Context, *InteractionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeComment not implemented")
}
func (UnimplementedInteractionServiceServer) UnlikeComment(context.Context, *InteractionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlikeComment not implemented")
}
func (UnimplementedInteractionServiceServer) mustEmbedUnimplementedInteractionServiceServer() {}
func (UnimplementedInteractionServiceServer) testEmbeddedByValue()                            {}

// UnsafeInteractionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InteractionServiceServer will
// result in compilation errors.
type UnsafeInteractionServiceServer interface {
	mustEmbedUnimplementedInteractionServiceServer()
}

func RegisterInteractionServiceServer(s grpc.ServiceRegistrar, srv InteractionServiceServer) {
	// If the following call panics, it indicates UnimplementedInteractionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InteractionService_ServiceDesc, srv)
}

func _InteractionService_LikePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).LikePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_LikePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).LikePost(ctx, req.(*InteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_UnlikePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).UnlikePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_UnlikePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).UnlikePost(ctx, req.(*InteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_CollectPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).CollectPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_CollectPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).CollectPost(ctx, req.(*InteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_UncollectPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).UncollectPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_UncollectPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).UncollectPost(ctx, req.(*InteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_RatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).RatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_RatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).RatePost(ctx, req.(*RateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_LikeComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).LikeComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_LikeComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).LikeComment(ctx, req.(*InteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_UnlikeComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).UnlikeComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_UnlikeComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).UnlikeComment(ctx, req.(*InteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InteractionService_ServiceDesc is the grpc.ServiceDesc for InteractionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InteractionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interaction.InteractionService",
	HandlerType: (*InteractionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LikePost",
			Handler:    _InteractionService_LikePost_Handler,
		},
		{
			MethodName: "UnlikePost",
			Handler:    _InteractionService_UnlikePost_Handler,
		},
		{
			MethodName: "CollectPost",
			Handler:    _InteractionService_CollectPost_Handler,
		},
		{
			MethodName: "UncollectPost",
			Handler:    _InteractionService_UncollectPost_Handler,
		},
		{
			MethodName: "RatePost",
			Handler:    _InteractionService_RatePost_Handler,
		},
		{
			MethodName: "LikeComment",
			Handler:    _InteractionService_LikeComment_Handler,
		},
		{
			MethodName: "UnlikeComment",
			Handler:    _InteractionService_UnlikeComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/interaction/interaction.proto",
}
