// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: notification/notification.proto

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 当前通知类型基本直接对应 platform-java 中的 NotificationType 枚举。
// 第一阶段先保证语义对齐，后续再由 notification-rpc 独立演进。
type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNKNOWN NotificationType = 0
	NotificationType_COMMENT                   NotificationType = 1
	NotificationType_REPLY                     NotificationType = 2
	NotificationType_LIKE_POST                 NotificationType = 3
	NotificationType_COLLECT_POST              NotificationType = 4
	NotificationType_RATE_POST                 NotificationType = 5
	NotificationType_LIKE_COMMENT              NotificationType = 6
	NotificationType_FOLLOW                    NotificationType = 7
	NotificationType_SYSTEM                    NotificationType = 8
	NotificationType_SYSTEM_AUDIT_PASS         NotificationType = 9
	NotificationType_SYSTEM_AUDIT_REJECT       NotificationType = 10
	NotificationType_SYSTEM_POST_DELETE        NotificationType = 11
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0:  "NOTIFICATION_TYPE_UNKNOWN",
		1:  "COMMENT",
		2:  "REPLY",
		3:  "LIKE_POST",
		4:  "COLLECT_POST",
		5:  "RATE_POST",
		6:  "LIKE_COMMENT",
		7:  "FOLLOW",
		8:  "SYSTEM",
		9:  "SYSTEM_AUDIT_PASS",
		10: "SYSTEM_AUDIT_REJECT",
		11: "SYSTEM_POST_DELETE",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNKNOWN": 0,
		"COMMENT":                   1,
		"REPLY":                     2,
		"LIKE_POST":                 3,
		"COLLECT_POST":              4,
		"RATE_POST":                 5,
		"LIKE_COMMENT":              6,
		"FOLLOW":                    7,
		"SYSTEM":                    8,
		"SYSTEM_AUDIT_PASS":         9,
		"SYSTEM_AUDIT_REJECT":       10,
		"SYSTEM_POST_DELETE":        11,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_notification_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_notification_notification_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{0}
}

// 面向 RPC 调用方返回的通知对象。
// created_at 使用 unix seconds，避免 Java/Go 在 LocalDateTime 字符串格式上额外对齐。
type Notification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReceiverId     int64                  `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	SenderId       int64                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderNickname string                 `protobuf:"bytes,4,opt,name=sender_nickname,json=senderNickname,proto3" json:"sender_nickname,omitempty"`
	SenderAvatar   string                 `protobuf:"bytes,5,opt,name=sender_avatar,json=senderAvatar,proto3" json:"sender_avatar,omitempty"`
	Type           NotificationType       `protobuf:"varint,6,opt,name=type,proto3,enum=notification.NotificationType" json:"type,omitempty"`
	TargetId       string                 `protobuf:"bytes,7,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetPreview  string                 `protobuf:"bytes,8,opt,name=target_preview,json=targetPreview,proto3" json:"target_preview,omitempty"`
	IsRead         bool                   `protobuf:"varint,9,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *Notification) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Notification) GetSenderNickname() string {
	if x != nil {
		return x.SenderNickname
	}
	return ""
}

func (x *Notification) GetSenderAvatar() string {
	if x != nil {
		return x.SenderAvatar
	}
	return ""
}

func (x *Notification) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNKNOWN
}

func (x *Notification) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Notification) GetTargetPreview() string {
	if x != nil {
		return x.TargetPreview
	}
	return ""
}

func (x *Notification) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Notification) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 给 notification-rpc 内部写入时使用的载荷。
// 第一阶段保持和当前 Java listener 组装的 NotificationDoc 语义一致。
type NotificationPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReceiverId     int64                  `protobuf:"varint,1,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	SenderId       int64                  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderNickname string                 `protobuf:"bytes,3,opt,name=sender_nickname,json=senderNickname,proto3" json:"sender_nickname,omitempty"`
	SenderAvatar   string                 `protobuf:"bytes,4,opt,name=sender_avatar,json=senderAvatar,proto3" json:"sender_avatar,omitempty"`
	Type           NotificationType       `protobuf:"varint,5,opt,name=type,proto3,enum=notification.NotificationType" json:"type,omitempty"`
	TargetId       string                 `protobuf:"bytes,6,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetPreview  string                 `protobuf:"bytes,7,opt,name=target_preview,json=targetPreview,proto3" json:"target_preview,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationPayload) Reset() {
	*x = NotificationPayload{}
	mi := &file_notification_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationPayload) ProtoMessage() {}

func (x *NotificationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationPayload.ProtoReflect.Descriptor instead.
func (*NotificationPayload) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{2}
}

func (x *NotificationPayload) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *NotificationPayload) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *NotificationPayload) GetSenderNickname() string {
	if x != nil {
		return x.SenderNickname
	}
	return ""
}

func (x *NotificationPayload) GetSenderAvatar() string {
	if x != nil {
		return x.SenderAvatar
	}
	return ""
}

func (x *NotificationPayload) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNKNOWN
}

func (x *NotificationPayload) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *NotificationPayload) GetTargetPreview() string {
	if x != nil {
		return x.TargetPreview
	}
	return ""
}

type GetUnreadCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountRequest) Reset() {
	*x = GetUnreadCountRequest{}
	mi := &file_notification_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountRequest) ProtoMessage() {}

func (x *GetUnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{3}
}

func (x *GetUnreadCountRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnreadCount   int64                  `protobuf:"varint,1,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountResponse) Reset() {
	*x = GetUnreadCountResponse{}
	mi := &file_notification_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountResponse) ProtoMessage() {}

func (x *GetUnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{4}
}

func (x *GetUnreadCountResponse) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_notification_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{5}
}

func (x *ListNotificationsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListNotificationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListNotificationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Notification        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_notification_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{6}
}

func (x *ListNotificationsResponse) GetItems() []*Notification {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListNotificationsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListNotificationsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListNotificationsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type MarkAllReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllReadRequest) Reset() {
	*x = MarkAllReadRequest{}
	mi := &file_notification_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllReadRequest) ProtoMessage() {}

func (x *MarkAllReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAllReadRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{7}
}

func (x *MarkAllReadRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MarkBatchReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Ids           []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkBatchReadRequest) Reset() {
	*x = MarkBatchReadRequest{}
	mi := &file_notification_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkBatchReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkBatchReadRequest) ProtoMessage() {}

func (x *MarkBatchReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkBatchReadRequest.ProtoReflect.Descriptor instead.
func (*MarkBatchReadRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{8}
}

func (x *MarkBatchReadRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MarkBatchReadRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// 普通通知：评论、回复、系统通知等，保持逐条写入。
type CreateNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *NotificationPayload   `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationRequest) Reset() {
	*x = CreateNotificationRequest{}
	mi := &file_notification_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationRequest) ProtoMessage() {}

func (x *CreateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationRequest.ProtoReflect.Descriptor instead.
func (*CreateNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{9}
}

func (x *CreateNotificationRequest) GetNotification() *NotificationPayload {
	if x != nil {
		return x.Notification
	}
	return nil
}

// 状态类通知：点赞、收藏、关注、评分等，需要按
// receiver_id + sender_id + type + target_id 进行 upsert 去重。
type UpsertNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *NotificationPayload   `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertNotificationRequest) Reset() {
	*x = UpsertNotificationRequest{}
	mi := &file_notification_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertNotificationRequest) ProtoMessage() {}

func (x *UpsertNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertNotificationRequest.ProtoReflect.Descriptor instead.
func (*UpsertNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{10}
}

func (x *UpsertNotificationRequest) GetNotification() *NotificationPayload {
	if x != nil {
		return x.Notification
	}
	return nil
}

// 预留给后续管理/数据修复使用。
type CleanDuplicateNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanDuplicateNotificationsRequest) Reset() {
	*x = CleanDuplicateNotificationsRequest{}
	mi := &file_notification_notification_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanDuplicateNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanDuplicateNotificationsRequest) ProtoMessage() {}

func (x *CleanDuplicateNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanDuplicateNotificationsRequest.ProtoReflect.Descriptor instead.
func (*CleanDuplicateNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{11}
}

type CleanDuplicateNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int64                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanDuplicateNotificationsResponse) Reset() {
	*x = CleanDuplicateNotificationsResponse{}
	mi := &file_notification_notification_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanDuplicateNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanDuplicateNotificationsResponse) ProtoMessage() {}

func (x *CleanDuplicateNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanDuplicateNotificationsResponse.ProtoReflect.Descriptor instead.
func (*CleanDuplicateNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{12}
}

func (x *CleanDuplicateNotificationsResponse) GetDeletedCount() int64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

var File_notification_notification_proto protoreflect.FileDescriptor

const file_notification_notification_proto_rawDesc = "" +
	"\n" +
	"\x1fnotification/notification.proto\x12\fnotification\"\a\n" +
	"\x05Empty\"\xda\x02\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\x03R\n" +
	"receiverId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x12'\n" +
	"\x0fsender_nickname\x18\x04 \x01(\tR\x0esenderNickname\x12#\n" +
	"\rsender_avatar\x18\x05 \x01(\tR\fsenderAvatar\x122\n" +
	"\x04type\x18\x06 \x01(\x0e2\x1e.notification.NotificationTypeR\x04type\x12\x1b\n" +
	"\ttarget_id\x18\a \x01(\tR\btargetId\x12%\n" +
	"\x0etarget_preview\x18\b \x01(\tR\rtargetPreview\x12\x17\n" +
	"\ais_read\x18\t \x01(\bR\x06isRead\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\"\x99\x02\n" +
	"\x13NotificationPayload\x12\x1f\n" +
	"\vreceiver_id\x18\x01 \x01(\x03R\n" +
	"receiverId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x03R\bsenderId\x12'\n" +
	"\x0fsender_nickname\x18\x03 \x01(\tR\x0esenderNickname\x12#\n" +
	"\rsender_avatar\x18\x04 \x01(\tR\fsenderAvatar\x122\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1e.notification.NotificationTypeR\x04type\x12\x1b\n" +
	"\ttarget_id\x18\x06 \x01(\tR\btargetId\x12%\n" +
	"\x0etarget_preview\x18\a \x01(\tR\rtargetPreview\"0\n" +
	"\x15GetUnreadCountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\";\n" +
	"\x16GetUnreadCountResponse\x12!\n" +
	"\funread_count\x18\x01 \x01(\x03R\vunreadCount\"d\n" +
	"\x18ListNotificationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x94\x01\n" +
	"\x19ListNotificationsResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.notification.NotificationR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"-\n" +
	"\x12MarkAllReadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"A\n" +
	"\x14MarkBatchReadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\"b\n" +
	"\x19CreateNotificationRequest\x12E\n" +
	"\fnotification\x18\x01 \x01(\v2!.notification.NotificationPayloadR\fnotification\"b\n" +
	"\x19UpsertNotificationRequest\x12E\n" +
	"\fnotification\x18\x01 \x01(\v2!.notification.NotificationPayloadR\fnotification\"$\n" +
	"\"CleanDuplicateNotificationsRequest\"J\n" +
	"#CleanDuplicateNotificationsResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x03R\fdeletedCount*\xeb\x01\n" +
	"\x10NotificationType\x12\x1d\n" +
	"\x19NOTIFICATION_TYPE_UNKNOWN\x10\x00\x12\v\n" +
	"\aCOMMENT\x10\x01\x12\t\n" +
	"\x05REPLY\x10\x02\x12\r\n" +
	"\tLIKE_POST\x10\x03\x12\x10\n" +
	"\fCOLLECT_POST\x10\x04\x12\r\n" +
	"\tRATE_POST\x10\x05\x12\x10\n" +
	"\fLIKE_COMMENT\x10\x06\x12\n" +
	"\n" +
	"\x06FOLLOW\x10\a\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\b\x12\x15\n" +
	"\x11SYSTEM_AUDIT_PASS\x10\t\x12\x17\n" +
	"\x13SYSTEM_AUDIT_REJECT\x10\n" +
	"\x12\x16\n" +
	"\x12SYSTEM_POST_DELETE\x10\v2\x95\x05\n" +
	"\x13NotificationService\x12[\n" +
	"\x0eGetUnreadCount\x12#.notification.GetUnreadCountRequest\x1a$.notification.GetUnreadCountResponse\x12d\n" +
	"\x11ListNotifications\x12&.notification.ListNotificationsRequest\x1a'.notification.ListNotificationsResponse\x12D\n" +
	"\vMarkAllRead\x12 .notification.MarkAllReadRequest\x1a\x13.notification.Empty\x12H\n" +
	"\rMarkBatchRead\x12\".notification.MarkBatchReadRequest\x1a\x13.notification.Empty\x12R\n" +
	"\x12CreateNotification\x12'.notification.CreateNotificationRequest\x1a\x13.notification.Empty\x12R\n" +
	"\x12UpsertNotification\x12'.notification.UpsertNotificationRequest\x1a\x13.notification.Empty\x12\x82\x01\n" +
	"\x1bCleanDuplicateNotifications\x120.notification.CleanDuplicateNotificationsRequest\x1a1.notification.CleanDuplicateNotificationsResponseB\x10Z\x0e./notificationb\x06proto3"

var (
	file_notification_notification_proto_rawDescOnce sync.Once
	file_notification_notification_proto_rawDescData []byte
)

func file_notification_notification_proto_rawDescGZIP() []byte {
	file_notification_notification_proto_rawDescOnce.Do(func() {
		file_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_notification_proto_rawDesc), len(file_notification_notification_proto_rawDesc)))
	})
	return file_notification_notification_proto_rawDescData
}

var file_notification_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_notification_notification_proto_goTypes = []any{
	(NotificationType)(0),                       // 0: notification.NotificationType
	(*Empty)(nil),                               // 1: notification.Empty
	(*Notification)(nil),                        // 2: notification.Notification
	(*NotificationPayload)(nil),                 // 3: notification.NotificationPayload
	(*GetUnreadCountRequest)(nil),               // 4: notification.GetUnreadCountRequest
	(*GetUnreadCountResponse)(nil),              // 5: notification.GetUnreadCountResponse
	(*ListNotificationsRequest)(nil),            // 6: notification.ListNotificationsRequest
	(*ListNotificationsResponse)(nil),           // 7: notification.ListNotificationsResponse
	(*MarkAllReadRequest)(nil),                  // 8: notification.MarkAllReadRequest
	(*MarkBatchReadRequest)(nil),                // 9: notification.MarkBatchReadRequest
	(*CreateNotificationRequest)(nil),           // 10: notification.CreateNotificationRequest
	(*UpsertNotificationRequest)(nil),           // 11: notification.UpsertNotificationRequest
	(*CleanDuplicateNotificationsRequest)(nil),  // 12: notification.CleanDuplicateNotificationsRequest
	(*CleanDuplicateNotificationsResponse)(nil), // 13: notification.CleanDuplicateNotificationsResponse
}
var file_notification_notification_proto_depIdxs = []int32{
	0,  // 0: notification.Notification.type:type_name -> notification.NotificationType
	0,  // 1: notification.NotificationPayload.type:type_name -> notification.NotificationType
	2,  // 2: notification.ListNotificationsResponse.items:type_name -> notification.Notification
	3,  // 3: notification.CreateNotificationRequest.notification:type_name -> notification.NotificationPayload
	3,  // 4: notification.UpsertNotificationRequest.notification:type_name -> notification.NotificationPayload
	4,  // 5: notification.NotificationService.GetUnreadCount:input_type -> notification.GetUnreadCountRequest
	6,  // 6: notification.NotificationService.ListNotifications:input_type -> notification.ListNotificationsRequest
	8,  // 7: notification.NotificationService.MarkAllRead:input_type -> notification.MarkAllReadRequest
	9,  // 8: notification.NotificationService.MarkBatchRead:input_type -> notification.MarkBatchReadRequest
	10, // 9: notification.NotificationService.CreateNotification:input_type -> notification.CreateNotificationRequest
	11, // 10: notification.NotificationService.UpsertNotification:input_type -> notification.UpsertNotificationRequest
	12, // 11: notification.NotificationService.CleanDuplicateNotifications:input_type -> notification.CleanDuplicateNotificationsRequest
	5,  // 12: notification.NotificationService.GetUnreadCount:output_type -> notification.GetUnreadCountResponse
	7,  // 13: notification.NotificationService.ListNotifications:output_type -> notification.ListNotificationsResponse
	1,  // 14: notification.NotificationService.MarkAllRead:output_type -> notification.Empty
	1,  // 15: notification.NotificationService.MarkBatchRead:output_type -> notification.Empty
	1,  // 16: notification.NotificationService.CreateNotification:output_type -> notification.Empty
	1,  // 17: notification.NotificationService.UpsertNotification:output_type -> notification.Empty
	13, // 18: notification.NotificationService.CleanDuplicateNotifications:output_type -> notification.CleanDuplicateNotificationsResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_notification_notification_proto_init() }
func file_notification_notification_proto_init() {
	if File_notification_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_notification_proto_rawDesc), len(file_notification_notification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_notification_proto_goTypes,
		DependencyIndexes: file_notification_notification_proto_depIdxs,
		EnumInfos:         file_notification_notification_proto_enumTypes,
		MessageInfos:      file_notification_notification_proto_msgTypes,
	}.Build()
	File_notification_notification_proto = out.File
	file_notification_notification_proto_goTypes = nil
	file_notification_notification_proto_depIdxs = nil
}
