# 使用 Alpine 版本以支持 apk 命令，且体积更小
# 如果 1.25-alpine 拉取失败，可临时改为 golang:alpine
FROM golang:1.25-alpine

WORKDIR /app

# 1. 预先下载依赖
COPY go.mod go.sum ./
# 配置国内代理
ARG GOPROXY=https://goproxy.cn,direct
ENV GOPROXY=${GOPROXY}
RUN go mod download

# 安装时区 (Alpine 使用 apk)
# 关键：将官方源替换为阿里云镜像源
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

# 这样安装速度会快非常多
RUN apk add --no-cache tzdata ca-certificates
ENV TZ=Asia/Shanghai

# 2. 复制源码
COPY . .

# 3. 开发环境运行
# 【关键修改】路径指向 cmd/sidecar/main.go
CMD ["go", "run", "./cmd/sidecar/main.go"]
