// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: comment.proto

package commentservice

import (
	"context"

	"comment-rpc/comment"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Comment                 = comment.Comment
	CommentPageResponse     = comment.CommentPageResponse
	CreateCommentRequest    = comment.CreateCommentRequest
	DeleteCommentRequest    = comment.DeleteCommentRequest
	Empty                   = comment.Empty
	ListRootCommentsRequest = comment.ListRootCommentsRequest
	ListSubCommentsRequest  = comment.ListSubCommentsRequest
	ReplyUser               = comment.ReplyUser
	SimpleUser              = comment.SimpleUser

	CommentService interface {
		CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*Comment, error)
		DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*Empty, error)
		ListRootComments(ctx context.Context, in *ListRootCommentsRequest, opts ...grpc.CallOption) (*CommentPageResponse, error)
		ListSubComments(ctx context.Context, in *ListSubCommentsRequest, opts ...grpc.CallOption) (*CommentPageResponse, error)
	}

	defaultCommentService struct {
		cli zrpc.Client
	}
)

func NewCommentService(cli zrpc.Client) CommentService {
	return &defaultCommentService{
		cli: cli,
	}
}

func (m *defaultCommentService) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*Comment, error) {
	client := comment.NewCommentServiceClient(m.cli.Conn())
	return client.CreateComment(ctx, in, opts...)
}

func (m *defaultCommentService) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := comment.NewCommentServiceClient(m.cli.Conn())
	return client.DeleteComment(ctx, in, opts...)
}

func (m *defaultCommentService) ListRootComments(ctx context.Context, in *ListRootCommentsRequest, opts ...grpc.CallOption) (*CommentPageResponse, error) {
	client := comment.NewCommentServiceClient(m.cli.Conn())
	return client.ListRootComments(ctx, in, opts...)
}

func (m *defaultCommentService) ListSubComments(ctx context.Context, in *ListSubCommentsRequest, opts ...grpc.CallOption) (*CommentPageResponse, error) {
	client := comment.NewCommentServiceClient(m.cli.Conn())
	return client.ListSubComments(ctx, in, opts...)
}
