// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	auth "gateway-api/internal/handler/auth"
	comment "gateway-api/internal/handler/comment"
	interaction "gateway-api/internal/handler/interaction"
	javaproxy "gateway-api/internal/handler/javaproxy"
	message "gateway-api/internal/handler/message"
	post "gateway-api/internal/handler/post"
	search "gateway-api/internal/handler/search"
	user "gateway-api/internal/handler/user"
	"gateway-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 后台管理接口：基本都直接代理给 Java。
	// 这里的网关职责主要是统一入口、鉴权、头透传和错误包装。
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/logout",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/refresh",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/reset-password",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/send-code",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/log/admin",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/log/export",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/log/user",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/post/:id",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/:id/audit",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/post/:postId",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/post/:postId/audit-history",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/:postId/audit/ai",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/audit-list",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/profile/info",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/profile/password",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/stats",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/stats/top-views",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/:id",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/:id",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/list",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: auth.LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/password/reset",
				Handler: auth.ResetPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/refresh",
				Handler: auth.RefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/send-code",
				Handler: auth.SendEmailCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/auth"),
	)

	// 评论接口已全部切到 comment-rpc，网关不再经过 Java controller。
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: comment.CreateCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: comment.DeleteCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: comment.ListCommentsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/sub-list",
				Handler: comment.SubListCommentsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/comment"),
	)

	// 通用上传接口直接代理给 Java。
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/upload",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/common"),
	)

	// 开发辅助接口直接代理。
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/clean-notifications",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/seed",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/dev"),
	)

	// interaction 接口不走 Java，直接打到 interaction-rpc。
	// 这里网关的职责主要是：
	// 1. 解析 HTTP 请求
	// 2. 从 context 取当前用户
	// 3. 调 RPC
	// 4. 返回统一响应
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/collect/post",
				Handler: interaction.CollectPostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/like/comment",
				Handler: interaction.LikeCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/like/post",
				Handler: interaction.LikePostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/rate/post",
				Handler: interaction.RatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/uncollect/post",
				Handler: interaction.UncollectPostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/unlike/comment",
				Handler: interaction.UnlikeCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/unlike/post",
				Handler: interaction.UnlikePostHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/interaction"),
	)

	// 帖子接口是网关职责最典型的一组：
	// 1. 创建/删除/更新仍然多由 Java 负责
	// 2. 列表/搜索/详情则由网关做聚合，把搜索结果和互动状态拼成统一前端视图
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/notifications",
				Handler: message.NotificationsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/read",
				Handler: message.ReadNotificationHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/read",
				Handler: message.BatchReadNotificationHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/unread-count",
				Handler: message.UnreadCountHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/message"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:postId",
				Handler: post.GetPostDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search",
				Handler: post.SearchPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search/suggest",
				Handler: post.SuggestHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/:userId",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/post"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/history",
				Handler: search.GetHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/history",
				Handler: search.ClearHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/history/item",
				Handler: search.DeleteHistoryItemHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/search"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/mongo-to-es",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/sync"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/ai-generate",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/hot",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/tag"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:userId/profile",
				Handler: user.GetPublicProfileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/bind-email",
				Handler: user.BindEmailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/collects",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comments",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/fans/:userId",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/follow",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/follows/:userId",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/friends",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/history",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/likes",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/password/change",
				Handler: user.ChangePasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/profile",
				Handler: user.GetProfileHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/profile",
				Handler: user.UpdateProfileHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ratings",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search",
				Handler: user.SearchUsersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/unfollow",
				Handler: javaproxy.ProxyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)
}
