// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: notification.proto

package notificationservice

import (
	"context"

	"notification-rpc/notification"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CleanDuplicateNotificationsRequest  = notification.CleanDuplicateNotificationsRequest
	CleanDuplicateNotificationsResponse = notification.CleanDuplicateNotificationsResponse
	CreateNotificationRequest           = notification.CreateNotificationRequest
	Empty                               = notification.Empty
	GetUnreadCountRequest               = notification.GetUnreadCountRequest
	GetUnreadCountResponse              = notification.GetUnreadCountResponse
	ListNotificationsRequest            = notification.ListNotificationsRequest
	ListNotificationsResponse           = notification.ListNotificationsResponse
	MarkAllReadRequest                  = notification.MarkAllReadRequest
	MarkBatchReadRequest                = notification.MarkBatchReadRequest
	Notification                        = notification.Notification
	NotificationPayload                 = notification.NotificationPayload
	UpsertNotificationRequest           = notification.UpsertNotificationRequest

	NotificationService interface {
		// 对应当前 /api/message/unread-count
		GetUnreadCount(ctx context.Context, in *GetUnreadCountRequest, opts ...grpc.CallOption) (*GetUnreadCountResponse, error)
		// 对应当前 /api/message/notifications
		ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...grpc.CallOption) (*ListNotificationsResponse, error)
		// 对应当前 /api/message/read (全部已读)
		MarkAllRead(ctx context.Context, in *MarkAllReadRequest, opts ...grpc.CallOption) (*Empty, error)
		// 对应当前 /api/message/read (批量已读)
		MarkBatchRead(ctx context.Context, in *MarkBatchReadRequest, opts ...grpc.CallOption) (*Empty, error)
		// 普通插入：评论、回复、系统类通知
		CreateNotification(ctx context.Context, in *CreateNotificationRequest, opts ...grpc.CallOption) (*Empty, error)
		// 去重 upsert：点赞、收藏、评分、关注类通知
		UpsertNotification(ctx context.Context, in *UpsertNotificationRequest, opts ...grpc.CallOption) (*Empty, error)
		// 仅供管理/数据修复使用，便于迁移旧数据时执行一次清洗。
		CleanDuplicateNotifications(ctx context.Context, in *CleanDuplicateNotificationsRequest, opts ...grpc.CallOption) (*CleanDuplicateNotificationsResponse, error)
	}

	defaultNotificationService struct {
		cli zrpc.Client
	}
)

func NewNotificationService(cli zrpc.Client) NotificationService {
	return &defaultNotificationService{
		cli: cli,
	}
}

// 对应当前 /api/message/unread-count
func (m *defaultNotificationService) GetUnreadCount(ctx context.Context, in *GetUnreadCountRequest, opts ...grpc.CallOption) (*GetUnreadCountResponse, error) {
	client := notification.NewNotificationServiceClient(m.cli.Conn())
	return client.GetUnreadCount(ctx, in, opts...)
}

// 对应当前 /api/message/notifications
func (m *defaultNotificationService) ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...grpc.CallOption) (*ListNotificationsResponse, error) {
	client := notification.NewNotificationServiceClient(m.cli.Conn())
	return client.ListNotifications(ctx, in, opts...)
}

// 对应当前 /api/message/read (全部已读)
func (m *defaultNotificationService) MarkAllRead(ctx context.Context, in *MarkAllReadRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := notification.NewNotificationServiceClient(m.cli.Conn())
	return client.MarkAllRead(ctx, in, opts...)
}

// 对应当前 /api/message/read (批量已读)
func (m *defaultNotificationService) MarkBatchRead(ctx context.Context, in *MarkBatchReadRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := notification.NewNotificationServiceClient(m.cli.Conn())
	return client.MarkBatchRead(ctx, in, opts...)
}

// 普通插入：评论、回复、系统类通知
func (m *defaultNotificationService) CreateNotification(ctx context.Context, in *CreateNotificationRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := notification.NewNotificationServiceClient(m.cli.Conn())
	return client.CreateNotification(ctx, in, opts...)
}

// 去重 upsert：点赞、收藏、评分、关注类通知
func (m *defaultNotificationService) UpsertNotification(ctx context.Context, in *UpsertNotificationRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := notification.NewNotificationServiceClient(m.cli.Conn())
	return client.UpsertNotification(ctx, in, opts...)
}

// 仅供管理/数据修复使用，便于迁移旧数据时执行一次清洗。
func (m *defaultNotificationService) CleanDuplicateNotifications(ctx context.Context, in *CleanDuplicateNotificationsRequest, opts ...grpc.CallOption) (*CleanDuplicateNotificationsResponse, error) {
	client := notification.NewNotificationServiceClient(m.cli.Conn())
	return client.CleanDuplicateNotifications(ctx, in, opts...)
}
